import { Geist, Geist_Mono, Lato, Montserrat, Great_Vibes} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollUp from "@/components/ScrollUp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-lato',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-montserrat',
})

const greatVibes = Great_Vibes({
  subsets: ['latin'],
  weight: ['400'], // Only one weight available
  display: 'swap',
  variable: '--font-great-vibes',
})

export const metadata = {
  title: "Home | Big Stars Animal Feed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} antialiased overflow-x-hidden`}
      >
        <Navbar />
        {children}
        <ScrollUp />
        <Footer />
        <script src="//code.tidio.co/pxep964yduadm2htcxvzg9dr73ttzysv.js" async></script>
      </body>
    </html>
  );
}
